### ISSUE TITLE
methods and variable names must follow python style guide

### ISSUE THREAD

**Issue by KiranSatyaRaj** [KiranSatyaRaj/mazesolver_py#1]
currently, the public variables and methods are a bit vague, and they aren't following the style convention for python(snake_case), it's good to follow them because it makes the code easier to read and work with

**Comment by PraddyumnYadav** [comment]
Sir Please **Describe it in more detail**. I Have some Problems Understanding it.

**Comment by KiranSatyaRaj** [comment]
Hey @PraddyumnYadav, thanks for stopping by and taking the time to raise this point, you can go through the project files, and see if there are any public variables or methods that aren't following the snake_case, which is the style convention for python, and if you do find them, you can change them to snake_case, please don't hesitate to reach out if you need any help regarding this issue

**Comment by PraddyumnYadav** [comment]
Sir @KiranSatyaRaj I am a Bigginner Can You **_Please Give Me More Information About This Project_** and i am Very Exited for this Project Because This is Going to be my First Github Open Source Contributions.

**Comment by KiranSatyaRaj** [comment]
> Sir @KiranSatyaRaj I am a Bigginner Can You **_Please Give Me More Information About This Project_** Like What is it? what we are going to do in it? and i am Very Exited for this Project Because This is Going to be my First Github Open Source Contributions.

Sorry for not being clear enough, there are public methods like `draw_line` and `redraw`, and also variables, apparently it should be `_draw_line` and `_redraw`, same goes for the variables as well, private methods or variables having `__` before the name need not be touched, look for such variables and methods and add put an underscore before, it's good to go through the class methods first and then go for its dependencies, like `cell` class in `cell.py` change that first and look for other files which import the cell class and its methods, and then go change the cell methods names in that file, repeat that for all the class, I hope that helps. feel free to reach out.

**Comment by PraddyumnYadav** [comment]
Thank You Sir for Your Explanation.

**Comment by KiranSatyaRaj** [comment]
> Thank You Sir for Your Explanation.

you can refer me as Kiran, and thanks for showing interest in this project @PraddyumnYadav, Happy contributing

**Comment by PraddyumnYadav** [comment]
Mr. Kiran According to You I Have Named all the python varibales and methodes in snake_case in this [Pull Request](https://github.com/KiranSatyaRaj/mazesolver_py/pull/3#issue-1535060184).
so if there are Any Problems Here So Feel Free to tell me That.

**Comment by PraddyumnYadav** [comment]
I have Solved this i issue in this [Pull Request](https://github.com/KiranSatyaRaj/mazesolver_py/pull/4#issue-1535276252) and yes this Time it is performing all the tests very well and drawing the grid in a way that upper left wall and lower right wall is open.
